# Chapter 5: Data Manipulation with Pandas

## 1. **Introduction to Pandas**
- Pandas is the foundational library for data manipulation and analysis in Python. 
- It provides high-performance, easy-to-use data structures and tools for working with structured data (tabular, time series, etc.).
- **Why Pandas?**
    - Handles millions of rows efficiently
    - Intuitive syntax (like SQL + Spreadsheets)
    - Seamless integration with machine learning pipelines
    - Built-in support for missing data, grouping, reshaping, and merging

## 2. **Installation and Import**
In window, open powershell or open terminal present in your IDEs (like VS Code (ctrl + J)) and wite the following command:

> pip install pandas

If you are using Linux, open terminal and write the command

#### Debian
> sudo apt-get install python3-pandas

#### Arch
> sudo pacman -S python3-pandas

Open the text file and write the following line to import panda in the system.

In [2]:
import pandas as pd

## 3. **Core Data Structure**
### 3.1 **Series (1-dimensional)**
- A labeled array (like a column in Excel).
- A **Series** is a one-dimensional labeled array capable of holding any data type.
- It is essentially a NumPy array with an attached index (label) for each element.

In [3]:
# Creating a series
sales = pd.Series([25000, 32000, 18000, 45000],
                  index = ['Q1', 'Q2', 'Q3', 'Q4'],
                  name='Quarterly Sales')
print(sales)

Q1    25000
Q2    32000
Q3    18000
Q4    45000
Name: Quarterly Sales, dtype: int64

### 3.2 **DataFrame (2-dimensional)**
- The heart of Pandas -- a table with rows and columns, each column a Series.
- A **DataFrame** is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure.
- Think of it as a spreadsheet, a SQL table, or **Dictionary** of Series object.

In [4]:
# Create from a Dictionary
data = {
    'Product':['Laptop', 'Phone', 'Tablet', 'Monitor'],
    'Sales':[45000, 32000, 18000, 25000],
    'Region': ['North', 'South', 'East', 'West'],
    'Data': pd.date_range('2026-01-01', periods=4,)
}
df = pd.DataFrame(data)
print(df)

   Product  Sales Region       Data
0   Laptop  45000  North 2026-01-01
1    Phone  32000  South 2026-01-02
2   Tablet  18000   East 2026-01-03
3  Monitor  25000   West 2026-01-04

* **Key attribute**
  - **df.shape** -> (rows, columns)
  - **df.columns**,**df.index**
  - **df.dtype**
  - **df.info()** and **df.describe()**
  
📝Note: Always run this Key Attributes first!!

## 4. Loading Real-World Data
- These are various types of file like: csv, json, sql.
- Panda library provides access of those file by applying followings

### 1. **Read CSV**
- CSV files are the Comma Seperated Files that allow storage of tabular data.
- To access data from the CSV fiel, you require **read_csv()** from Pandas that retrives data in the form of the data frame.

In [ ]:
peoples = 'https://media.geeksforgeeks.org/wp-content/uploads/20241121154629307916/people_data.csv'

- Pandas allows you to directly read a CSV file hosted on the internet using the file url.
- The following URL (**people_data.csv** from geeksforgeeks) is indicated by **peoples**

In [ ]:
import pandas as pd
df = pd.read_csv(peoples)
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

- **read_csv()** function in Pandas is used to read data from CSV file into a Panda DataFrame.
- CSV files are plain-text files where each row represents a record, and columns are separated by commas.
- **Syntax**:
> pd.read_csv(filepath_or_buffer, sep=',', header='infer', index_col=None, usecols=None, engine=None, skiprows=None, nrows=None)

- **Parameters**:
    - **filepath_or_buffer**: Location of the csv file. It accepts any string path or URL of the file.
    - **sep**: It stands for seperator, default is ',' (comma).
    - **header**: It accepts int, a list of int, row numbers to use as the column names, and the start of the data. If no names are passed, i.e., header=None, then, it will display the first column as 0, the second as 1 and so on.
    - **usecols**: Retrieves only selected columns from the CSV file.
    - **nrows**: Number of rows to be displayed from the dataset.
    - **index_col**: If None, there are no index numbers displayed along with records.
    - **skiprows**: Skips passed rows in the new data frame.

### Features in Pandas read_csv
1. Read specific columns using read_csv
    - The usecols parameter allows to load only specific columns from a CSV file. This reduces memory usage and processing time by importing only the required data.

In [ ]:
df = pd.read_csv(peoples, usecols=['First Name', 'Email'])
df

  First Name                       Email
0     Shelby        elijah57@example.net
1    Phillip       bethany14@example.com
2   Kristine       bthompson@example.com
3    Yesenia   kaitlinkaiser@example.com
4       Lori  buchananmanuel@example.net

2. Setting an index Column (index_col)
    - The index_col parameter sets one or more columns as the DataFrame index, making the specified column(s) act as row labels for easier data referencing.

In [ ]:
df = pd.read_csv(peoples, index_col='First Name')
df

,Last Name,Sex,Email,Date of birth,Job Title
First Name,,,,,
Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

3. Handling Missing Values Using read_csv
    - The na_values parameter replaces specified strings (e.g "N/A", "Unknown") with NaN, enabling consistent handling of missing or incomplete data during analysis.

In [ ]:
df = pd.read_csv(peoples, na_values=["N/A", "Unknown"])
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

- We do not have N/A, Unknown or ? dataset in the Peoples csv. So lets import 'auto.csv' file and express theses missing statements

- using download CSV file name.

In [ ]:
df = pd.read_csv('auto.csv', na_values=['?','N/A','Unknown'])
df

,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
2,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
3,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,15250.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
200,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
201,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
202,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
203,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

4. Reading CSV Files with Different Delimiters
    - In this example, we will take a CSV file and then add some special characters to see how the sep parameter works.

In [ ]:
import pandas as pd

data = """totalbill_tip, sex:smoker, day_time, size
16.99, 1.01:Female|No, Sun, Dinner, 2
10.34, 1.66, Male, No|Sun:Dinner, 3
21.01:3.5_Male, No:Sun, Dinner, 3
23.68, 3.31, Male|No, Sun_Dinner, 2
24.59:3.61, Female_No, Sun, Dinner, 4
25.29, 4.71|Male, No:Sun, Dinner, 4"""

with open("sample.csv", "w") as file:
    file.write(data)
print(data)

totalbill_tip, sex:smoker, day_time, size
16.99, 1.01:Female|No, Sun, Dinner, 2
10.34, 1.66, Male, No|Sun:Dinner, 3
21.01:3.5_Male, No:Sun, Dinner, 3
23.68, 3.31, Male|No, Sun_Dinner, 2
24.59:3.61, Female_No, Sun, Dinner, 4
25.29, 4.71|Male, No:Sun, Dinner, 4

- The sample data is stored in a multi-line string for demonstration purpose.
    1. **Seperator** (sep): The sep='[:,|_]' argument allows Pandas to handle multiple delimiters (:,|,_,,) using a regular expression.
    2. **Engine**: The engine='python' argument is used because the default C engine does not support regular expressions for delimiters.

In [ ]:
df = pd.read_csv('sample.csv',
                 sep='[:, |_]',
                 engine='python')
df

,totalbill,tip,Unnamed: 2,sex,smoker,Unnamed: 5,day,time,Unnamed: 8,size
16.99,NaN,1.01,Female,No,NaN,Sun,NaN,Dinner,NaN,2.0
10.34,NaN,1.66,NaN,Male,NaN,No,Sun,Dinner,NaN,3.0
21.01,3.50,Male,NaN,No,Sun,NaN,Dinner,NaN,3.0,NaN
23.68,NaN,3.31,NaN,Male,No,NaN,Sun,Dinner,NaN,2.0
24.59,3.61,NaN,Female,No,NaN,Sun,NaN,Dinner,NaN,4.0
25.29,NaN,4.71,Male,NaN,No,Sun,NaN,Dinner,NaN,4.0

5. Using nrows in read_csv()
    - The nrows parameter limits the number of rows read from a file, enabling quick previews or partial data loading for large datasets. 
    - Here, we display only 5 rows using nrows parameter.

In [ ]:
df = pd.read_csv(peoples, nrows=3)
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath

6. Using skiprows in read_csv
    - The skiprows parameter skips unnecessary rows at the start of a file, which is useful for ignoring metadata or extra headers that are not part of the dataset.

In [ ]:
df = pd.read_csv(peoples)
print("Previous DataSets:")
print(df)

Previous DataSets:
  First Name Last Name     Sex                       Email Date of birth  \
0     Shelby   Terrell    Male        elijah57@example.net    1945-10-26
1    Phillip   Summers  Female       bethany14@example.com    1910-03-24
2   Kristine    Travis    Male       bthompson@example.com    1992-07-02
3    Yesenia  Martinez    Male   kaitlinkaiser@example.com    2017-08-03
4       Lori      Todd    Male  buchananmanuel@example.net    1938-12-01

            Job Title
0     Games developer
1      Phytotherapist
2           Homeopath
3   Market researcher
4  Veterinary surgeon

In [ ]:
df = pd.read_csv(peoples, skiprows=[4,5])
print("DataSets after skipping rows:")
print(df)

DataSets after skipping rows:
  First Name Last Name     Sex                  Email Date of birth  \
0     Shelby   Terrell    Male   elijah57@example.net    1945-10-26
1    Phillip   Summers  Female  bethany14@example.com    1910-03-24
2   Kristine    Travis    Male  bthompson@example.com    1992-07-02

         Job Title
0  Games developer
1   Phytotherapist
2        Homeopath

7. Parsing Dates (parse_dates)
    - The parse_dates parameter converts data columns into datetime objects, simplifying operations like filtering, sorting, or time-based analysis.

In [ ]:
df = pd.read_csv(peoples, parse_dates=['Date of birth'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   First Name     5 non-null      object
 1   Last Name      5 non-null      object
 2   Sex            5 non-null      object
 3   Email          5 non-null      object
 4   Date of birth  5 non-null      datetime64[ns]
 5   Job Title      5 non-null      object
dtypes: datetime64[ns](1), object(5)
memory usage: 372.0+ bytes

### II. Read Excel
- Excel files store data in rows and columns, making them useful for managing structured datasets.
- To work with **Excel** file in Python, we use the Pandas library which allows us to read, modify and analyze Excel data in DataFrame.
- Similarly to the read_csv, we use **read_excel()** function to load Excel data into Python for processing.

In [ ]:
students = 'https://media.geeksforgeeks.org/wp-content/uploads/20260218173335806406/students.xlsx'

- An URl from GeeksForGeeks.

In [ ]:
import pandas as pd

df = pd.read_excel(students)
df

   Roll No.  English  Maths  Science
0         1       19     13       17
1         2       14     20       18
2         3       15     18       19
3         4       13     14       14
4         5       17     16       20
5         6       19     13       17
6         7       14     20       18
7         8       15     18       19
8         9       13     14       14
9        10       17     16       20

### Loading Multiple Sheets using concat()
- By default, read_excel() loads only the first sheet of an Excel workbook.
- If file contains multiple sheets, you can read each sheet seperately and then combine them in single DataFrame using **pd.concat()**.
- The read_excel() function provides useful arguments to control how dat is loaded:
    1. sheet_name: Specifying the name of the sheet that needs to be used.
    2. index_col: Defines the column to be used as the index.

For example:

In [ ]:
sheet1 = pd.read_excel(students,
                       sheet_name= 0,
                       index_col = 0)
sheet1

          English  Maths  Science
Roll No.
1              19     13       17
2              14     20       18
3              15     18       19
4              13     14       14
5              17     16       20
6              19     13       17
7              14     20       18
8              15     18       19
9              13     14       14
10             17     16       20

In [ ]:
sheet2 = pd.read_excel(students,
                       sheet_name=1,
                       index_col=0)
sheet2

          English  Maths  Science
Roll No.
1              14     18       20
2              11     19       18
3              12     18       16
4              15     18       19
5              13     14       14
6              14     18       20
7              11     19       18
8              12     18       16
9              15     18       19
10             13     14       14

In [ ]:
newData = pd.concat([sheet1, sheet2])
newData

          English  Maths  Science
Roll No.
1              19     13       17
2              14     20       18
3              15     18       19
4              13     14       14
5              17     16       20
6              19     13       17
7              14     20       18
8              15     18       19
9              13     14       14
10             17     16       20
1              14     18       20
2              11     19       18
3              12     18       16
4              15     18       19
5              13     14       14
6              14     18       20
7              11     19       18
8              12     18       16
9              15     18       19
10             13     14       14

### Head and Tail method
- The head() and tail() methods are used to quickly preview data in a DataFrame.
- Helps you to inspect the top or bottom rows without printing the entire dataset.
  - **head()**: Displays the first 5 rows by default
  - **tail()**: Displays the last 5 rows by default

In [ ]:
newData.head()

          English  Maths  Science
Roll No.
1              19     13       17
2              14     20       18
3              15     18       19
4              13     14       14
5              17     16       20

In [ ]:
newData.tail()

          English  Maths  Science
Roll No.
6              14     18       20
7              11     19       18
8              12     18       16
9              15     18       19
10             13     14       14

### Shape() method
- The shape attribute is used to check the dimensions of a DataFrame.
- Returns a **tuple** showing the total number of rows and columns.

In [ ]:
newData.shape

(20, 3)

- First value represents the number of rows.
- Second value represents the number of columns

### Sort_values() method
- Used to sort a DataFrame based on the values of a specific column.
- It is especially useful when working with numerical data, but it can also sort text data.
- Sorts values in ascending order, for descending order use ascending=False.

In [ ]:
sorted_column = newData.sort_values(['English'], ascending=True)
sorted_column.head()

          English  Maths  Science
Roll No.
7              11     19       18
2              11     19       18
8              12     18       16
3              12     18       16
10             13     14       14

In [ ]:
newData['Maths'].head()

Roll No.
1    13
2    20
3    18
4    14
5    16
Name: Maths, dtype: int64

### Describe() method
- When dataset contains numerical data, the describe() method provides a quick statistical summary of the DataFrame.
- It includes:
    1. Count
    2. Mean
    3. Standard Deviation
    4. Minimum and Maximum values
    5. percentiles

In [ ]:
newData.describe()

        English      Maths    Science
count  20.00000  20.000000  20.000000
mean   14.30000  16.800000  17.500000
std     2.29645   2.330575   2.164304
min    11.00000  13.000000  14.000000
25%    13.00000  14.000000  16.000000
50%    14.00000  18.000000  18.000000
75%    15.00000  18.000000  19.000000
max    19.00000  20.000000  20.000000

- Pandas also provides individual statistical methods like mean(), sum(), min(), and max() to calculate specific values.

In [ ]:
newData['Maths'].mean()

np.float64(16.8)

- Can also create calculated columns, like Excel formulas, by performing operations on existing columns.

In [ ]:
newData['Total Marks'] = newData['Maths'] + newData["English"] + newData["Science"]
newData['Total Marks'].head()

Roll No.
1    49
2    52
3    52
4    41
5    53
Name: Total Marks, dtype: int64

- After operating on the data in the data frame, we can export the data back to an Excel file using the method **to_excel**.

In [ ]:
newData.to_excel('output.xlsx')

![Output](output.xlsx.png)

- It creates a new file if it doesn't exist.
- Overwrites the file of a file with the same name already exists.

## III. Read JSON
- JSON (JavaScript Object Notation) store data using key-value pairs.
- There are mainly three methods to read Json file using Pandas Some of them are:

1. Using pd.read_json()
- The pd.read_json() function helps to read JSON data directly into a DataFrame.
- If the file is located on a remote server we can also pass the URL instead of a local file path.

In [ ]:
json_data = 'data.json'

In [ ]:
import pandas as pd

df = pd.read_json(json_data)
df.head()

   id                     name     location  val
0   1   Arduno-thermosensor-t1  Coding-room   26
1   2   Arduno-thermosensor-t2  Server-room   55
2   3  Arduino-thermosensor-t3      Kitchen   25

2. Using json Module and pd.json_normalize()
- The **.json_normalize()** is used when we are working with nested JSON structure.
- JSON from APIs often comes in nested form and this method helps to flatten it into a tabular format that's easier to work.
- This method is helpful when working with real world JSON responses from APIs.

In [ ]:
import pandas as pd
import json

data = {"One": {"0": 60, "1": 60, "2": 60, "3": 45, "4": 45, "5": 60},
        "Two": {"0": 110, "1": 117, "2": 103, "3": 109, "4": 117, "5": 102}
}

json_data = json.dumps(data)

df_normalize = pd.json_normalize(json.loads(json_data))
print("\nDataFrame using JSON module and `pd.json_normalize()` method:")
df_normalize

DataFrame using JSON module and `pd.json_normalize()` method:

,One.0,One.1,One.2,One.3,One.4,One.5,Two.0,Two.1,Two.2,Two.3,Two.4,Two.5
0,60,60,60,45,45,60,110,117,103,109,117,102

3. using pd.DataFrame with dictionary
- If JSON data is stored as a dictionary you can use pd.DataFrame() convert it into a structured DataFrame.

In [ ]:
data = {"One": {"0": 60, "1": 60, "2": 60, "3": 45, "4": 45, "5": 60},
        "Two": {"0": 110, "1": 117, "2": 103, "3": 109, "4": 117, "5": 102}
}
df=pd.DataFrame(data)
df

   One  Two
0   60  110
1   60  117
2   60  103
3   45  109
4   45  117
5   60  102

## 5. Data Indexing and Selection
The most common mistake new data scientists make is misunderstanding how to slice data. Pandas provides two highly optimized access methods:

1. **.loc** (**Local-based**): You access rows and columns by their explicit labels (names).
2. **.iloc** (**Integer-based**): You access rows and columns by their implicit integer position (like a standard array).

In [5]:
import numpy as np
data = {
    'Sensor_ID':['ESP_01', 'ESP_02', 'ESP_01', 'ESP_03', 'ESP_02'],
    'Temperature_c':[22.4, 23.4, 22.6, np.nan,23.0],
    'Status': ['active','active','active','offline','active']
}
df = pd.DataFrame(data)

In [6]:
# Slicing and Dicing

# 1. Accessing a column ( returns a Series)
temperature = df['Temperature_c']

# 2. Accessing a row by index position using .iloc
first_row = df.iloc[0]
print(f"iloc:\n{first_row}")

# 3. Accessing a subset of rows and specific columns using .loc
# Format: df.loc[row_labels, column_labels]
active_sensors = df.loc[0:2,['Sensor_ID', 'Status']]
print(f"loc:\n{active_sensors}")

iloc:
Sensor_ID        ESP_01
Temperature_c      22.4
Status           active
Name: 0, dtype: object
loc:
  Sensor_ID  Status
0    ESP_01  active
1    ESP_02  active
2    ESP_01  active

## Boolean Indexing (Filtering)
- To filter data, we pass a boolean array (a mask) directly into the DataFrame. This is highly optimized and avoids slow Python **for** loops.

In [7]:
# Create a mask: Which rows have temperature greater than 22.5
high_temp_mask = df['Temperature_c'] > 22.5
print(f"Temperature greater than 22.5: {high_temp_mask}")

Temperature greater than 22.5: 0    False
1     True
2     True
3    False
4     True
Name: Temperature_c, dtype: bool

In [8]:
# Apply the mask to filter the DataFrame
hot_sensors_df = df[high_temp_mask]
print(f"Filtered DataFrame: {hot_sensors_df}")

Filtered DataFrame:   Sensor_ID  Temperature_c  Status
1    ESP_02           23.4  active
2    ESP_01           22.6  active
4    ESP_02           23.0  active

In [9]:
# Pro-tip: Combine conditions using bitwise operations (& for AND, | for OR)
# Always wrap conditions in parantheses !!
critical_sensors = df[(df['Temperature_c']>22.5) & (df['Status'] == 'active')]
print(f'Critical value:\n {critical_sensors}')

Critical value:
   Sensor_ID  Temperature_c  Status
1    ESP_02           23.4  active
2    ESP_01           22.6  active
4    ESP_02           23.0  active

## 6. Data Cleaning and Imputation
- Real-world data is messy. Sensors fail, network packets drop, and user inputs are flawed.
- Handling missing data (represented as NaN - Not a Number) is a critical step before feeding data into any machine learning model.
- Imputation is the fancy data science term for "filling in the blanks".

- The **isna()** function scans your DataFrame or Series and returns a "mask" of the same shape, where each cell is either True (missing) or False (not missing).
- In pandas, *isnull()* is just an alias for *isna()*.

In [10]:
# Handling missing data
missing_mask = df.isna() # Returns a DataFrame of True/False
print(f"Missing masks: {missing_mask}")

Missing masks:    Sensor_ID  Temperature_c  Status
0      False          False   False
1      False          False   False
2      False          False   False
3      False           True   False
4      False          False   False

- Counting missing values: Usually, you don't want to look at a giant wall of **True/False**. you want to know how many values are missing. you can chain .sum() to end:

In [11]:
df.isna().sum()

Sensor_ID        0
Temperature_c    1
Status           0
dtype: int64

- the **dropna()** is used to filter out rows or columns that contain NaN or null values. Because most machine learning models and statistical functions can't handle missing data, this is one of the most common steps in data cleaning.

In [12]:
# 2. Drop rows with any missing values
clear_off = df.dropna()
print(clear_off)

  Sensor_ID  Temperature_c  Status
0    ESP_01           22.4  active
1    ESP_02           23.4  active
2    ESP_01           22.6  active
4    ESP_02           23.0  active

- If you want to find the data that is actually there, use **notna()** (or its alias **notnull()**)

- While **.dropna()** simply throws away rows with missing values, imputation uses logic or statistics to replace those NaN values with a reasonable guess. This allows you to keep your dataset size intact, which is crucial when your data is limited or when the missingness follows a pattern.

In [13]:
# 3. Imputation: Fill missing values with a logical default
# Here, we fill the missing temperature with the mean of the column
mean_temp = df['Temperature_c'].mean()
df['Temperature_c'] = df['Temperature_c'].fillna(mean_temp)
print(df)

  Sensor_ID  Temperature_c   Status
0    ESP_01          22.40   active
1    ESP_02          23.40   active
2    ESP_01          22.60   active
3    ESP_03          22.85  offline
4    ESP_02          23.00   active